version: '3'

# ============================================================================ #

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception_network
    env_file: .env
    image: nginx
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception_network
    env_file: .env
    image: mariadb
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception_network
    env_file: .env
    image: wordpress

# ============================================================================ #

networks:

  inception_network:
    name: inception_network

# ============================================================================ #

volumes:

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/aruiz-mo/data/wp
  
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/aruiz-mo/data/db